### ISSUE TITLE
unrealistic prices

### ISSUE THREAD

**Issue by senoyches** [BigFood2307/FS22_DynamicFieldPrices#7] opened 2022-08-01 00:39 UTC
Hello Bigfoot,

some prices are very unrealistic, I am currently player on NF Marsch.
![dynamicfieldprices001](https://user-images.githubusercontent.com/106155205/182052090-277c5fe3-2d9e-4808-93c2-dba5e8209366.png)
![dynamicfieldprices002](https://user-images.githubusercontent.com/106155205/182052091-549e361d-8b60-41a9-a01d-29a898346618.png)

Here are two screenshots of these cases. 100% Discount is a little bit two much. And the other way ist 1090% Overprized?

I am not sure if I have understood your description correctly. 
You write something about an economic factor of between 0.6-1.6, and greediness of 0.8-1.2.
From this I calculate that the maximum 
... markup is 1.2x1.6 = 192% of the original price.
... discount is 0.8x0.6 = 48% before original price, so I can not explain these values as seen above.

Mfg
Senoyches

**Comment by BigFood2307** [comment] 2022-09-13 10:17
Youre calculations are correct. With just the map (2.2) and Dynamic Field Prices I cant reproduce the error. The map uses a lot of different priceScales, but that should be fine with my mod.
Have you tested combinations of different mods?
Or has it been resolved by a map update?

**Closed as completed** 2023-07-26 12:19 UTC
