### ISSUE TITLE
Zero "Difference"

### ISSUE THREAD

**Issue by tuzlo** [BigFood2307/FS22_DynamicFieldPrices#6] opened 2022-05-26 14:41 UTC
I am having an issue with a certain map I am playing. The map is Spring Creek ND, a 32x map. The majority of my fields have a difference of 0% and it never changes. Have  done something wrong? Is there a way to make the rest of the fields fluctuate in price?

**Comment by BigFood2307** [comment] 2023-07-26 13:05
Hi!

Sorry for the very long wait. I have not been playing FS at all. I just loaded up this map and it works as intended. That could be from an update, Im not sure.
For now Im closing this issue unless someone can replicate it

**Closed as not planned by BigFood2307** 2023-07-26 13:05 UTC
