### ISSUE TITLE
Making a field more expensive, if it is ready to harvest

### ISSUE THREAD

**Issue by Malaras** [BigFood2307/FS22_DynamicFieldPrices#8] opened 2022-09-07 17:45 UTC
Would love This!

**Comment by BigFood2307** [comment] 2023-07-26 12:44
I am thinking of this, but I have to get much better at lua and FS modding specifically to do it. Have not seen a super easy way to check to status of a field/farmland.
Closing this, since it is a Duplicate of #5

**Closed as not planned by BigFood2307** 2023-07-26 12:44 UTC
