### ISSUE TITLE
Error after saving modmap

### ISSUE THREAD

**Issue by oggimaster** [BigFood2307/FS22_DynamicFieldPrices#4] opened 2022-03-28 13:34 UTC
Hello there,

I have an issue, where after saving my modmap, leaving to menu and starting the map back again, all overlays in the ESC menu are bugged - I cant get out of the menu anymore or close the game via "leave game" button.

-> the mod works fine with the original maps

I narrowed the problem down to your mod. While it isnt active, everything works fine.
I get following error message which spams in the console:

_Error: Running LUA method 'update'.
dataS/scripts/gui/InGameMenuMapFrame.lua(493) : attempt to index field 'mapOverlayGenerator' (a nil value)_

Maybe you have an idea how to fix it. Because it works with the original maps but not with my map, maybe there is something that "collides" with each other.

**Comment by Mr-Frost1** [comment] 2022-08-22 00:20
Had this same issue, I found a German Giants forum about what I presume is a map (NF March) that has the same issue. I think it has to do with NPCS based off what the Forum post says. I copied the google translate and pasted it below. Ill be honest I don't have a lot of interest in trying to fix the mod for myself but it looks like they potentially found a fix.

Today I wrote to FedAction about why the error on the NF march occurs in connection with the mod "Dynamic Field Prices" or similar mods that have something to do with NPCs and their field assignments. Maybe it will be fixed. In my case, the Dynamic Field Prices mod caused the broken menu error. However, the cause lies in the map NF Marsch. There, 2 NPCs were not assigned farmland to start a game. The error is probably only noticeable if you use mods that do exactly what with it. At least I haven't seen the bug on the NF march without mods so far. Presumably, the 2 NPCs are old remnants and should have been deleted, at least these 2 NPCs are not used anywhere.
To fix the error yourself, the NF march must be unpacked and the file map_npcs.xml in the maps/ folder must be adjusted. Lines 18 and 19 must be deleted from the file. (applies to NF Marsch 4x version 2.0 for the FS22) The content of these 2 lines is as follows: After that, the customized file must be copied back into the zipped NF Marsch Map and overwritten. If you start the map now and install the mod everything runs fine, at least for me. Maybe the adaptation of the file will also help others here to solve the problems. Have fun.

**Comment by Mr-Frost1** [comment] 2022-08-22 00:20
https://forum.giants-software.com/viewtopic.php?t=190770 

There's a link to the full forum

**Comment by mlaidma** [comment] 2022-08-31 21:11
Here for the same reason. Trying to use this mod with the map Brzozówka and running into the same errors as descripted by the German forum as well as the people above. 

Would be great to have a fix for that as I would really enjoy playing with this mod.

**Comment by Mr-Frost1** [comment] 2022-09-01 02:48
> Here for the same reason. Trying to use this mod with the map Brzozówka and running into the same errors as descripted by the German forum as well as the people above.
> 
> Would be great to have a fix for that as I would really enjoy playing with this mod.

Agreed, it does work perfectly on the base game maps though. It's something with the AI's from what I've read. If you are knowledgeable in modding (unlike myself) you may be able to find how to fix it. I think it has been done before based on google translating the forum I posted.

**Comment by mlaidma** [comment] 2022-09-01 12:23
Based on what was said in the giants forum, the reason seems to be a few NPCs that are included in the map, but don't have a single field assigned to them. As for fixing this manually for your current savegame, you can find the NPC list in your mod map, but how to know which ones will not be used for whatever reason? I guess just experimenting is an option. Albeit seriously time-consuming. Looking at the logs didnt really reveal anything obvious to an untrained eye, but I didnt also take a very long look.

I guess then first we'd need to figure out whether this bug occuring is the responsibility of this mod (not handling this case properly) or in the map (leaving unassigned/unused NPCs behind in their source). I dont know if I have the time to investigate this further at this point. 

Perhaps @BigFood2307 can help us further a bit?

**Comment by BigFood2307** [comment] 2022-09-01 12:36
Hey everyone,
I have not been playing recently, so I kind of ignored the mod. But this seems more of a problem, than I thought. I don't have access to a computer with FS for the next ~10 days, but I promise to look into it afterwards. 
The mod misbehaved on modmaps from the begining, eg. The display of the price change is misplaced and I never had any idea why. The additional field info mod had the same issue. 
So I can't promise I'll find a solution, but I will try.

**Comment by BigFood2307** [comment] 2022-09-13 07:54
@Mr-Frost1 
@mlaidma
Ok, so here are my results, when testing with the Brzozówka map:
I can solve the issue by adjusting the npcs.xml file of the map.
However I can not fix the issue in my mod. It obviously partially causes the problem, but I have no idea how. I only ever check the npcs, that are attached to a field, so that should work just fine...
I can only assume, that my messing with the mapOverlayGenerator causes some collision, with the base code, since the actual error does not happen in my mod, but in a base game file.
Why this only happens when NPCs are not properly assigned is a mystery to me. Currently I can not give a solution through my mod, but I can decribe how one can easily correct the maps:

1. Find the npcs.xml file in the maps folder in the mod-map archive.
2. Find the farmlands.xml file in the same folder
3. check each NPC Name for appearance in the farmlands file (just Ctrl-F)
4. If one NPC Name doesnt show up, delete the corresponding line from the npcs file
5. Save the npcs file and the archive, start a new game on the map
6. Profit

Sorry, that I cant provide anything better, I just dont really know what is going on in the background here...
Obviously I might just be missing some mistake in my code as well :D

**Comment by Mr-Frost1** [comment] 2022-09-13 14:34
@BigFood2307 
Thanks for your effort in trying to fix this issue. I agree with your conclusion that it has something to do with the mapOverlayGenerator but I haven't a clue as to why it only happens with NPCs not being assigned(I fully admit my lack of knowledge in modding and coding but still thought id give my input lol). I'm glad we were able to find some sort of a solution for this even though it's not optimal. Thanks again for your response and effort.

**Comment by BigFood2307** [comment] 2023-08-10 13:05
Thanks to @KITT3000 this is now fixed on the current main branch.
Modhub will take a while, since a update is already on it way...

**Closed as completed by BigFood2307** 2023-08-10 13:05 UTC
